In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.decomposition import PCA 
import matplotlib.pyplot as plt
import seaborn as sns 

In [5]:
import pandas as pd
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, confusion_matrix

x_all = []
y_all = []

dir1 = r"C:\Users\ashmi\OneDrive\Desktop\MS Thesis\shreya didi\classification_multiclass"
dir2 = r"C:\Users\ashmi\OneDrive\Desktop\MS Thesis\shreya didi\BB84_classData_theor_3class_withDelta_0"

for data_id in range(0, 50):
    file_name = f"BB84_classData_theor_3class_withDelta_{data_id}.csv"

    df1 = pd.read_csv(os.path.join(dir1, file_name))
    df2 = pd.read_csv(os.path.join(dir2, file_name))

    # ------------------------------
    # Safety checks
    # ------------------------------
    if len(df1) != len(df2):
        raise ValueError(f"Row mismatch in file {file_name}")

    if not df1['class'].equals(df2['class']):
        raise ValueError(f"Class mismatch in file {file_name}")

    # ------------------------------
    # Merge features (drop duplicate class column)
    # ------------------------------
    X_merged = pd.concat(
        [df1.drop('class', axis=1),
         df2.drop('class', axis=1)],
        axis=1
    )

    y = df1['class']

    x_all.append(X_merged)
    y_all.append(y)

# Final dataset
X = pd.concat(x_all, axis=0, ignore_index=True)
y = pd.concat(y_all, axis=0, ignore_index=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

pca = PCA(n_components=3)
x_pca_train = pca.fit_transform(X_train_scaled)
x_pca_test  = pca.transform(X_test_scaled)

for k in range(1, 21):
    clf = KNeighborsClassifier(n_neighbors=k)
    clf.fit(x_pca_train, y_train)

    train_score = clf.score(x_pca_train, y_train)
    test_score  = clf.score(x_pca_test, y_test)

    print(f"k = {k}: Train Acc = {train_score:.4f}, Test Acc = {test_score:.4f}")


k = 1: Train Acc = 1.0000, Test Acc = 0.9990
k = 2: Train Acc = 0.9995, Test Acc = 0.9992
k = 3: Train Acc = 0.9995, Test Acc = 0.9993
k = 4: Train Acc = 0.9994, Test Acc = 0.9993
k = 5: Train Acc = 0.9994, Test Acc = 0.9994
k = 6: Train Acc = 0.9994, Test Acc = 0.9994
k = 7: Train Acc = 0.9994, Test Acc = 0.9994
k = 8: Train Acc = 0.9994, Test Acc = 0.9994
k = 9: Train Acc = 0.9994, Test Acc = 0.9994
k = 10: Train Acc = 0.9994, Test Acc = 0.9994
k = 11: Train Acc = 0.9994, Test Acc = 0.9994
k = 12: Train Acc = 0.9994, Test Acc = 0.9994
k = 13: Train Acc = 0.9994, Test Acc = 0.9994
k = 14: Train Acc = 0.9994, Test Acc = 0.9994
k = 15: Train Acc = 0.9994, Test Acc = 0.9994
k = 16: Train Acc = 0.9994, Test Acc = 0.9994
k = 17: Train Acc = 0.9994, Test Acc = 0.9994
k = 18: Train Acc = 0.9994, Test Acc = 0.9994
k = 19: Train Acc = 0.9994, Test Acc = 0.9994
k = 20: Train Acc = 0.9994, Test Acc = 0.9994


In [ ]:
# depolarisationa  and bit flip binary

In [25]:
import pandas as pd
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, confusion_matrix


x_all = []
y_all = []

dir1 = r"C:\Users\ashmi\OneDrive\Desktop\MS Thesis\shreya didi\classification_multiclass"
dir2 = r"C:\Users\ashmi\OneDrive\Desktop\MS Thesis\shreya didi\BB84_classData_theor_3class_withDelta_0"

for data_id in range(0, 50):
    file_name = f"BB84_classData_theor_3class_withDelta_{data_id}.csv"

    df1 = pd.read_csv(os.path.join(dir1, file_name))
    df2 = pd.read_csv(os.path.join(dir2, file_name))

    # ------------------------------
    # Safety checks
    # ------------------------------
    if len(df1) != len(df2):
        raise ValueError(f"Row mismatch in file {file_name}")

    if not df1['class'].equals(df2['class']):
        raise ValueError(f"Class mismatch in file {file_name}")

    # ------------------------------
    # Merge features (drop duplicate class column)
    # ------------------------------
    X_merged = pd.concat(
        [df1.drop('class', axis=1),
         df2.drop('class', axis=1)],
        axis=0
    )

    y = pd.concat(
    [df1['class'],
     df2['class']],
    axis=0,
    ignore_index=True
    )

    x_all.append(X_merged)
    y_all.append(y)

X_full = pd.concat(x_all, axis=0, ignore_index=True)
y_full = pd.concat(y_all, axis=0, ignore_index=True)

X = pd.concat([
    X_full.iloc[:20000],
    X_full.iloc[40000:]
], axis=0)

y = pd.concat([
    y_full.iloc[:20000],
    y_full.iloc[40000:]
], axis=0)




X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

pca = PCA(n_components=3)
x_pca_train = pca.fit_transform(X_train_scaled)
x_pca_test  = pca.transform(X_test_scaled)



# -------------------------------------------------------
# Train and evaluate KNN for k=1 to 10
# -------------------------------------------------------
k=3
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_pca_train, y_train)

train_score = clf.score(x_pca_train, y_train)
test_score  = clf.score(x_pca_test, y_test)


train_score_list.append(train_score)
test_score_list.append(test_score)

# Optional: show confusion matrix for each k
y_pred = clf.predict(x_pca_test)
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))




Confusion matrix:
 [[399827    173      0]
 [   183 393496   2321]
 [     0   3723 396277]]


In [29]:
len(y), len(X)

(5979998, 5979998)

In [30]:
ave_train_score= np.average(train_score_list)
sem_train_score= np.std(train_score_list)

ave_test_score= np.average(test_score_list)
sem_test_score= np.std(test_score_list)

In [31]:
ave_test_score , ave_train_score, sem_train_score , sem_test_score

(0.9967785117056855,
 0.9977727812947922,
 0.0017622780483455378,
 0.0025797365484677517)

In [ ]:
#  depolarisation and amplitude dample - binary classification

In [36]:
import pandas as pd
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, confusion_matrix


x_all = []
y_all = []

dir1 = r"C:\Users\ashmi\OneDrive\Desktop\MS Thesis\shreya didi\classification_multiclass"
dir2 = r"C:\Users\ashmi\OneDrive\Desktop\MS Thesis\shreya didi\BB84_classData_theor_3class_withDelta_0"

for data_id in range(0, 50):
    file_name = f"BB84_classData_theor_3class_withDelta_{data_id}.csv"

    df1 = pd.read_csv(os.path.join(dir1, file_name))
    df2 = pd.read_csv(os.path.join(dir2, file_name))

    # ------------------------------
    # Safety checks
    # ------------------------------
    if len(df1) != len(df2):
        raise ValueError(f"Row mismatch in file {file_name}")

    if not df1['class'].equals(df2['class']):
        raise ValueError(f"Class mismatch in file {file_name}")

    # ------------------------------
    # Merge features (drop duplicate class column)
    # ------------------------------
    X_merged = pd.concat(
        [df1.drop('class', axis=1),
         df2.drop('class', axis=1)],
        axis=0
    )

    y = pd.concat(
    [df1['class'],
     df2['class']],
    axis=0,
    ignore_index=True
    )

    x_all.append(X_merged)
    y_all.append(y)

X_full = pd.concat(x_all, axis=0, ignore_index=True)
y_full = pd.concat(y_all, axis=0, ignore_index=True)

X = X_full.iloc[:40000]
y = y_full.iloc[:40000]



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

pca = PCA(n_components=3)
x_pca_train = pca.fit_transform(X_train_scaled)
x_pca_test  = pca.transform(X_test_scaled)



# -------------------------------------------------------
# Train and evaluate KNN for k=1 to 10
# -------------------------------------------------------
k=3
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_pca_train, y_train)

train_score = clf.score(x_pca_train, y_train)
test_score  = clf.score(x_pca_test, y_test)


train_score_list.append(train_score)
test_score_list.append(test_score)

# Optional: show confusion matrix for each k
y_pred = clf.predict(x_pca_test)
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))


Confusion matrix:
 [[4000    0]
 [   1 3999]]


In [37]:
ave_train_score= np.average(train_score_list)
sem_train_score= np.std(train_score_list)

ave_test_score= np.average(test_score_list)
sem_test_score= np.std(test_score_list)
print(len(X), len(y),ave_train_score , sem_train_score, ave_test_score, sem_test_score)

40000 40000 0.997877192462578 0.0017896758115094704 0.9969184185379838 0.002596940765166017


In [ ]:
# amplitude dampling and bit flip

In [32]:
import pandas as pd
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, confusion_matrix


x_all = []
y_all = []

dir1 = r"C:\Users\ashmi\OneDrive\Desktop\MS Thesis\shreya didi\classification_multiclass"
dir2 = r"C:\Users\ashmi\OneDrive\Desktop\MS Thesis\shreya didi\BB84_classData_theor_3class_withDelta_0"

for data_id in range(0, 50):
    file_name = f"BB84_classData_theor_3class_withDelta_{data_id}.csv"

    df1 = pd.read_csv(os.path.join(dir1, file_name))
    df2 = pd.read_csv(os.path.join(dir2, file_name))

    # ------------------------------
    # Safety checks
    # ------------------------------
    if len(df1) != len(df2):
        raise ValueError(f"Row mismatch in file {file_name}")

    if not df1['class'].equals(df2['class']):
        raise ValueError(f"Class mismatch in file {file_name}")

    # ------------------------------
    # Merge features (drop duplicate class column)
    # ------------------------------
    X_merged = pd.concat(
        [df1.drop('class', axis=1),
         df2.drop('class', axis=1)],
        axis=0
    )

    y = pd.concat(
    [df1['class'],
     df2['class']],
    axis=0,
    ignore_index=True
    )

    x_all.append(X_merged)
    y_all.append(y)

X_full = pd.concat(x_all, axis=0, ignore_index=True)
y_full = pd.concat(y_all, axis=0, ignore_index=True)

X = X_full.iloc[20002:]
y = y_full.iloc[20002:]



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

pca = PCA(n_components=3)
x_pca_train = pca.fit_transform(X_train_scaled)
x_pca_test  = pca.transform(X_test_scaled)



# -------------------------------------------------------
# Train and evaluate KNN for k=1 to 10
# -------------------------------------------------------
k=3
clf = KNeighborsClassifier(n_neighbors=k)
clf.fit(x_pca_train, y_train)

train_score = clf.score(x_pca_train, y_train)
test_score  = clf.score(x_pca_test, y_test)


train_score_list.append(train_score)
test_score_list.append(test_score)

# Optional: show confusion matrix for each k
y_pred = clf.predict(x_pca_test)
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))


Confusion matrix:
 [[395865    135      0]
 [   180 397476   2344]
 [     0   3726 396274]]


In [33]:
ave_train_score= np.average(train_score_list)
sem_train_score= np.std(train_score_list)

ave_test_score= np.average(test_score_list)
sem_test_score= np.std(test_score_list)
print(len(X), len(y),ave_train_score , sem_train_score, ave_test_score, sem_test_score)


5979998 5979998 0.9975285995396743 0.0016988653804022916 0.996425654960981 0.0024836277151915847
